CREATE DATABASE REDHEAD;
USE REDHEAD;

CREATE TABLE CLIENTE(
	cpf VARCHAR(15) PRIMARY KEY NOT NULL,
    idCliente INT NOT NULL,
	nomeCliente VARCHAR(100) NOT NULL,
	endereco VARCHAR(150) NOT NULL,
    dataNascimento VARCHAR(10) NOT NULL,
    codProjeto INT NOT NULL REFERENCES PROJETO(codProjeto)
    
);

ALTER TABLE CLIENTE ADD INDEX(idCliente);
ALTER TABLE CLIENTE CHANGE idCliente idCliente INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE PROJETO(
	codProjeto INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomeProjeto VARCHAR(45) NOT NULL,
    prazo VARCHAR(10) NOT NULL,
    equipe INT NOT NULL,
    valorTotal FLOAT NOT NULL,
    cpfFuncionario VARCHAR(15) NOT NULL REFERENCES FUNCIONARIO(cpf),
    codDepartamento INT NOT NULL REFERENCES DEPARTAMENTO(codDepartamento)
    
);

CREATE TABLE DEPARTAMENTO(
	codDepartamento INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomeDepartamento VARCHAR(45) NOT NULL,
    numeroFuncionario INT NOT NULL
);

CREATE TABLE FUNCIONARIO(
	nomeFuncionario VARCHAR(100) NOT NULL,
    cpf VARCHAR(15) NOT NULL PRIMARY KEY,
    endereco VARCHAR(150) NOT NULL,
    registro INT NOT NULL,
    dataNascimento VARCHAR(10) NOT NULL,
    salario FLOAT NOT NULL,
    cargo VARCHAR(45) NOT NULL,
    codDepartamento INT NOT NULL REFERENCES DEPARTAMENTO(codDepartamento),
    loginFuncionario VARCHAR(40) NOT NULL REFERENCES USUARIO(login),
    senhaFuncionario VARCHAR(45) NOT NULL REFERENCES USUARIO(senha)
);

CREATE TABLE SUPORTE(
	codAtendimento INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipoReclamacao VARCHAR(45) NOT NULL,
    motivoReclamacao VARCHAR(100) NOT NULL,
    nomeClienteAtendido VARCHAR(100) NOT NULL,
    cpfCliente VARCHAR(15) NOT NULL REFERENCES CLIENTE(cpf),
    cpfFuncionario VARCHAR(15) NOT NULL REFERENCES FUNCIONARIO(cpf),
    codProjeto INT NOT NULL REFERENCES PROJETO(codProjeto)
    
);

CREATE TABLE USUARIO(
    login VARCHAR(40) NOT NULL PRIMARY KEY,
    senha VARCHAR(45) NOT NULL
);

