CREATE DATABASE REDHEAD;
USE REDHEAD;

CREATE TABLE CLIENTE(
	idCliente INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nomeCliente VARCHAR(100) NOT NULL,
	cpf VARCHAR(15) NOT NULL,
	endereco VARCHAR(150) NOT NULL,
	dataNascimento VARCHAR(10) NOT NULL,
	codProjeto INT NOT NULL REFERENCES PROJETO(codProjeto),
	bairro VARCHAR(45) NOT NULL,
	cep VARCHAR(45) NOT NULL,
	cidade VARCHAR(45) NOT NULL,
	estado VARCHAR(45) NOT NULL
);
CREATE TABLE USUARIO(
	idUsuario INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	login VARCHAR(40) NOT NULL,
	senha VARCHAR(45) NOT NULL
);
CREATE TABLE PROJETO(
	codProjeto INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nomeProjeto VARCHAR(45) NOT NULL,
	prazo VARCHAR(10) NOT NULL,
	equipe INT NOT NULL,
	valorTotal FLOAT NOT NULL,
	cpfFuncionario VARCHAR(15) NOT NULL REFERENCES FUNCIONARIO(cpf),
	codDepartamento INT NOT NULL REFERENCES DEPARTAMENTO(codDepartamento),
	cpfCliente VARCHAR(15) NOT NULL,	
    nomeCliente VARCHAR(50) NOT NULL
);
CREATE TABLE DEPARTAMENTO(
	codDepartamento INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nomeDepartamento VARCHAR(45) NOT NULL,
	numeroFuncionario INT NOT NULL,
	responsavelDepartamento VARCHAR(45) NOT NULL,
	inicioAtividades VARCHAR(10) NOT NULL
);
CREATE TABLE FUNCIONARIO(
	nomeFuncionario VARCHAR(100) NOT NULL,
	cpf VARCHAR(15) PRIMARY KEY NOT NULL,
	endereco VARCHAR(150) NOT NULL,
	registro INT NOT NULL,
	dataNascimento VARCHAR(10),
	salario FLOAT NOT NULL,
	cargo VARCHAR(45) NOT NULL,
	codDepartamento INT NOT NULL REFERENCES DEPARTAMENTO(codDepartamento),
	cep VARCHAR(45) NOT NULL,
	cidade VARCHAR(45) NOT NULL,
	estado VARCHAR(45) NOT NULL,
    fotoPerfil VARCHAR(200),
    idFuncionario INT REFERENCES USUARIO(idUsuario)
);
ALTER TABLE FUNCIONARIO ADD INDEX(idFuncionario);
ALTER TABLE FUNCIONARIO CHANGE idFuncionario idFuncionario INT NOT NULL AUTO_INCREMENT;
CREATE TABLE SUPORTE(
	codAtendimento INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	tipoReclamacao VARCHAR(45) NOT NULL,
	motivoReclamacao VARCHAR(100) NOT NULL,
	nomeCliente VARCHAR(100) NOT NULL,
    cpfCliente VARCHAR(15) NOT NULL REFERENCES CLIENTE(cpf),
	cpfFuncionario VARCHAR(15) NOT NULL REFERENCES FUNCIONARIO(cpf),
	codProjeto INT NOT NULL REFERENCES PROJETO(codProjeto)
);